### ISSUE TITLE
Use Resource#sha256, Formula.sha256, SoftwareSpec#sha256, 

### ISSUE THREAD

**Issue by ajslater** [theseal/homebrew-ssh-askpass#5]
Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/iveney/homebrew-mocha/realpath.rb:11:in `class:Realpath'
Please report this to the iveney/mocha tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/theseal/homebrew-ssh-askpass/Formula/ssh-askpass.rb:6:in `class:SshAskpass'
Please report this to the theseal/ssh-askpass tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/theseal/homebrew-ssh-askpass/Formula/ssh-askpass.rb:6:in `class:SshAskpass'
Please report this to the theseal/ssh-askpass tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/theseal/homebrew-ssh-askpass/Formula/ssh-askpass.rb:6:in `class:SshAskpass'
Please report this to the theseal/ssh-askpass tap!

**Comment by theseal** [comment]
Will look in to is ASAP. Thanks. 🙃
